//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinerMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsiTakvimi
    {
        public int AsiID { get; set; }
        public Nullable<int> HayvanID { get; set; }
        public Nullable<System.DateTime> YapilisTarihi { get; set; }
        public Nullable<System.DateTime> TekrarTarihi { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    
        public virtual Hayvan Hayvan { get; set; }
        public virtual Profil Profil { get; set; }
    }
}
