//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinerMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hayvan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hayvan()
        {
            this.AsiTakvimi = new HashSet<AsiTakvimi>();
            this.Randevular = new HashSet<Randevular>();
            this.TedaviEkle = new HashSet<TedaviEkle>();
        }
    
        public int HayvanID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public string HayvanAdi { get; set; }
        public string HayvanTuru { get; set; }
        public string HayvanIrki { get; set; }
        public string Cinsiyeti { get; set; }
        public Nullable<byte> HayvanYasi { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsiTakvimi> AsiTakvimi { get; set; }
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevular> Randevular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TedaviEkle> TedaviEkle { get; set; }
        public virtual Profil Profil { get; set; }
    }
}
